### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by mdegis** [buraktekin/Amoeba#1]
We have a crappy interface. YEY!

**Comment by berkatmaca** [comment]
abi çok iyi ya!

**Comment by buraktekin** [comment]
adamım başlıyor muyuz?

2013/10/18 Berk Atmaca notifications@github.com

> abi çok iyi ya!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openall/Amoeba/issues/1#issuecomment-26560272
> .

## 

_Burak Tekin_
_Department of Computer Science_
